from enum import IntEnum

#
# === PIXEL MODES ===
#

class PixelMode(IntEnum):
    CHAFA_PIXEL_MODE_SYMBOLS = 0
    CHAFA_PIXEL_MODE_SIXELS  = 1
    CHAFA_PIXEL_MODE_KITTY   = 2
    CHAFA_PIXEL_MODE_ITERM2  = 3
    CHAFA_PIXEL_MODE_MAX     = 4


#
# === CANVAS MODES ===
#

class CanvasMode(IntEnum):
    CHAFA_CANVAS_MODE_TRUECOLOR     = 0
    CHAFA_CANVAS_MODE_INDEXED_256   = 1
    CHAFA_CANVAS_MODE_INDEXED_240   = 2
    CHAFA_CANVAS_MODE_INDEXED_16    = 3
    CHAFA_CANVAS_MODE_FGBG_BGFG     = 4
    CHAFA_CANVAS_MODE_FGBG          = 5
    CHAFA_CANVAS_MODE_INDEXED_8     = 6
    CHAFA_CANVAS_MODE_INDEXED_16_8  = 7

    CHAFA_CANVAS_MODE_MAX           = 8


#
# === DITHER MODES ===
#

class DitherMode(IntEnum):
    CHAFA_DITHER_MODE_NONE      = 0
    CHAFA_DITHER_MODE_ORDERED   = 1
    CHAFA_DITHER_MODE_DIFFUSION = 2

    CHAFA_DITHER_MODE_MAX       = 3


#
# === COLOR SPACE ===
#

class ColorSpace(IntEnum):
    CHAFA_COLOR_SPACE_RGB    = 0
    CHAFA_COLOR_SPACE_DIN99D = 1

    CHAFA_COLOR_SPACE_MAX    = 2


#
# === COLOR EXTRACTOR ===
#

class ColorExtractor(IntEnum):
    CHAFA_COLOR_EXTRACTOR_AVERAGE = 0
    CHAFA_COLOR_EXTRACTOR_MEDIAN  = 1

    CHAFA_COLOR_SPACE_MAX         = 2


#
# === OPTIMIZATIONS ===
#

class Optimizations(IntEnum):
    CHAFA_OPTIMIZATION_REUSE_ATTRIBUTES = (1 << 0),
    CHAFA_OPTIMIZATION_SKIP_CELLS       = (1 << 1),
    CHAFA_OPTIMIZATION_REPEAT_CELLS     = (1 << 2),

    CHAFA_OPTIMIZATION_NONE             = 0,
    CHAFA_OPTIMIZATION_ALL              = 0x7fffffff


#
# === PIXEL TYPE ===
#

class PixelType(IntEnum):
    CHAFA_PIXEL_RGBA8_PREMULTIPLIED = 0
    CHAFA_PIXEL_BGRA8_PREMULTIPLIED = 1
    CHAFA_PIXEL_ARGB8_PREMULTIPLIED = 2
    CHAFA_PIXEL_ABGR8_PREMULTIPLIED = 3

    CHAFA_PIXEL_RGBA8_UNASSOCIATED = 4
    CHAFA_PIXEL_BGRA8_UNASSOCIATED = 5
    CHAFA_PIXEL_ARGB8_UNASSOCIATED = 6
    CHAFA_PIXEL_ABGR8_UNASSOCIATED = 7
    
    CHAFA_PIXEL_RGB8 = 8
    CHAFA_PIXEL_BGR8 = 9
    CHAFA_PIXEL_MAX  = 10


#
# === SYMBOL TAGS ===
#

class SymbolTags(IntEnum):
    CHAFA_SYMBOL_TAG_NONE        = 0

    CHAFA_SYMBOL_TAG_SPACE       = (1 <<  0)
    CHAFA_SYMBOL_TAG_SOLID       = (1 <<  1)
    CHAFA_SYMBOL_TAG_STIPPLE     = (1 <<  2)
    CHAFA_SYMBOL_TAG_BLOCK       = (1 <<  3)
    CHAFA_SYMBOL_TAG_BORDER      = (1 <<  4)
    CHAFA_SYMBOL_TAG_DIAGONAL    = (1 <<  5)
    CHAFA_SYMBOL_TAG_DOT         = (1 <<  6)
    CHAFA_SYMBOL_TAG_QUAD        = (1 <<  7)
    CHAFA_SYMBOL_TAG_HHALF       = (1 <<  8)
    CHAFA_SYMBOL_TAG_VHALF       = (1 <<  9)
    CHAFA_SYMBOL_TAG_HALF        = ((CHAFA_SYMBOL_TAG_HHALF) | (CHAFA_SYMBOL_TAG_VHALF))
    CHAFA_SYMBOL_TAG_INVERTED    = (1 << 10)
    CHAFA_SYMBOL_TAG_BRAILLE     = (1 << 11)
    CHAFA_SYMBOL_TAG_TECHNICAL   = (1 << 12)
    CHAFA_SYMBOL_TAG_GEOMETRIC   = (1 << 13)
    CHAFA_SYMBOL_TAG_ASCII       = (1 << 14)
    CHAFA_SYMBOL_TAG_ALPHA       = (1 << 15)
    CHAFA_SYMBOL_TAG_DIGIT       = (1 << 16)
    CHAFA_SYMBOL_TAG_ALNUM       = CHAFA_SYMBOL_TAG_ALPHA | CHAFA_SYMBOL_TAG_DIGIT
    CHAFA_SYMBOL_TAG_NARROW      = (1 << 17)
    CHAFA_SYMBOL_TAG_WIDE        = (1 << 18)
    CHAFA_SYMBOL_TAG_AMBIGUOUS   = (1 << 19)
    CHAFA_SYMBOL_TAG_UGLY        = (1 << 20)
    CHAFA_SYMBOL_TAG_LEGACY      = (1 << 21)
    CHAFA_SYMBOL_TAG_SEXTANT     = (1 << 22)
    CHAFA_SYMBOL_TAG_WEDGE       = (1 << 23)
    CHAFA_SYMBOL_TAG_LATIN       = (1 << 24)
    CHAFA_SYMBOL_TAG_EXTRA       = (1 << 30)
    CHAFA_SYMBOL_TAG_BAD         = CHAFA_SYMBOL_TAG_AMBIGUOUS | CHAFA_SYMBOL_TAG_UGLY
    CHAFA_SYMBOL_TAG_ALL         = ~(CHAFA_SYMBOL_TAG_EXTRA | CHAFA_SYMBOL_TAG_BAD)


#
# === Term sequences ===
#

class TermSeq(IntEnum):
    CHAFA_TERM_SEQ_RESET_TERMINAL_SOFT = 0
    CHAFA_TERM_SEQ_RESET_TERMINAL_HARD = 1
    CHAFA_TERM_SEQ_RESET_ATTRIBUTES    = 2

    CHAFA_TERM_SEQ_CLEAR         = 3
    CHAFA_TERM_SEQ_INVERT_COLORS = 4

    CHAFA_TERM_SEQ_CURSOR_TO_TOP_LEFT    = 5
    CHAFA_TERM_SEQ_CURSOR_TO_BOTTOM_LEFT = 6
    CHAFA_TERM_SEQ_CURSOR_TO_POS         = 7
    CHAFA_TERM_SEQ_CURSOR_UP_1           = 8
    CHAFA_TERM_SEQ_CURSOR_UP             = 9
    CHAFA_TERM_SEQ_CURSOR_DOWN_1         = 10
    CHAFA_TERM_SEQ_CURSOR_DOWN           = 11
    CHAFA_TERM_SEQ_CURSOR_LEFT_1         = 12
    CHAFA_TERM_SEQ_CURSOR_LEFT           = 13
    CHAFA_TERM_SEQ_CURSOR_RIGHT_1        = 14
    CHAFA_TERM_SEQ_CURSOR_RIGHT          = 15
    CHAFA_TERM_SEQ_CURSOR_UP_SCROLL      = 16
    CHAFA_TERM_SEQ_CURSOR_DOWN_SCROLL    = 17

    CHAFA_TERM_SEQ_INSERT_CELLS = 18
    CHAFA_TERM_SEQ_DELETE_CELLS = 19
    CHAFA_TERM_SEQ_INSERT_ROWS  = 20
    CHAFA_TERM_SEQ_DELETE_ROWS  = 21

    CHAFA_TERM_SEQ_SET_SCROLLING_ROWS = 22

    CHAFA_TERM_SEQ_ENABLE_INSERT  = 23
    CHAFA_TERM_SEQ_DISABLE_INSERT = 24

    CHAFA_TERM_SEQ_ENABLE_CURSOR  = 25
    CHAFA_TERM_SEQ_DISABLE_CURSOR = 26

    CHAFA_TERM_SEQ_ENABLE_ECHO  = 27
    CHAFA_TERM_SEQ_DISABLE_ECHO = 28

    CHAFA_TERM_SEQ_ENABLE_WRAP  = 29
    CHAFA_TERM_SEQ_DISABLE_WRAP = 30

    CHAFA_TERM_SEQ_SET_COLOR_FG_DIRECT   = 31
    CHAFA_TERM_SEQ_SET_COLOR_BG_DIRECT   = 32
    CHAFA_TERM_SEQ_SET_COLOR_FGBG_DIRECT = 33

    CHAFA_TERM_SEQ_SET_COLOR_FG_256   = 34
    CHAFA_TERM_SEQ_SET_COLOR_BG_256   = 35
    CHAFA_TERM_SEQ_SET_COLOR_FGBG_256 = 36

    CHAFA_TERM_SEQ_SET_COLOR_FG_16   = 37
    CHAFA_TERM_SEQ_SET_COLOR_BG_16   = 38
    CHAFA_TERM_SEQ_SET_COLOR_FGBG_16 = 39

    CHAFA_TERM_SEQ_BEGIN_SIXELS = 40
    CHAFA_TERM_SEQ_END_SIXELS   = 41
    CHAFA_TERM_SEQ_REPEAT_CHAR  = 42

    CHAFA_TERM_SEQ_BEGIN_KITTY_IMMEDIATE_IMAGE_V1 = 43
    CHAFA_TERM_SEQ_END_KITTY_IMAGE                = 44
    CHAFA_TERM_SEQ_BEGIN_KITTY_IMAGE_CHUNK        = 45
    CHAFA_TERM_SEQ_END_KITTY_IMAGE_CHUNK          = 46

    CHAFA_TERM_SEQ_BEGIN_ITERM2_IMAGE = 47
    CHAFA_TERM_SEQ_END_ITERM2_IMAGE   = 48

    CHAFA_TERM_SEQ_ENABLE_SIXEL_SCROLLING  = 49
    CHAFA_TERM_SEQ_DISABLE_SIXEL_SCROLLING = 50

    CHAFA_TERM_SEQ_ENABLE_BOLD = 51

    CHAFA_TERM_SEQ_SET_COLOR_FG_8   = 52
    CHAFA_TERM_SEQ_SET_COLOR_BG_8   = 53
    CHAFA_TERM_SEQ_SET_COLOR_FGBG_8 = 54

    CHAFA_TERM_SEQ_RESET_DEFAULT_FG    = 55
    CHAFA_TERM_SEQ_SET_DEFAULT_FG      = 56
    CHAFA_TERM_SEQ_QUERY_DEFAULT_FG    = 57
    CHAFA_TERM_SEQ_RESET_DEFAULT_BG    = 58
    CHAFA_TERM_SEQ_SET_DEFAULT_BG      = 59
    CHAFA_TERM_SEQ_QUERY_DEFAULT_BG    = 60

    CHAFA_TERM_SEQ_RETURN_KEY          = 61
    CHAFA_TERM_SEQ_BACKSPACE_KEY       = 62
    CHAFA_TERM_SEQ_TAB_KEY             = 63
    CHAFA_TERM_SEQ_TAB_SHIFT_KEY       = 64
    CHAFA_TERM_SEQ_UP_KEY              = 65
    CHAFA_TERM_SEQ_UP_CTRL_KEY         = 66
    CHAFA_TERM_SEQ_UP_SHIFT_KEY        = 67
    CHAFA_TERM_SEQ_DOWN_KEY            = 68
    CHAFA_TERM_SEQ_DOWN_CTRL_KEY       = 69
    CHAFA_TERM_SEQ_DOWN_SHIFT_KEY      = 70
    CHAFA_TERM_SEQ_LEFT_KEY            = 71
    CHAFA_TERM_SEQ_LEFT_CTRL_KEY       = 72
    CHAFA_TERM_SEQ_LEFT_SHIFT_KEY      = 73
    CHAFA_TERM_SEQ_RIGHT_KEY           = 74
    CHAFA_TERM_SEQ_RIGHT_CTRL_KEY      = 75
    CHAFA_TERM_SEQ_RIGHT_SHIFT_KEY     = 76
    CHAFA_TERM_SEQ_PAGE_UP_KEY         = 77
    CHAFA_TERM_SEQ_PAGE_UP_CTRL_KEY    = 78
    CHAFA_TERM_SEQ_PAGE_UP_SHIFT_KEY   = 79
    CHAFA_TERM_SEQ_PAGE_DOWN_KEY       = 80
    CHAFA_TERM_SEQ_PAGE_DOWN_CTRL_KEY  = 81
    CHAFA_TERM_SEQ_PAGE_DOWN_SHIFT_KEY = 82
    CHAFA_TERM_SEQ_HOME_KEY            = 83
    CHAFA_TERM_SEQ_HOME_CTRL_KEY       = 84
    CHAFA_TERM_SEQ_HOME_SHIFT_KEY      = 85
    CHAFA_TERM_SEQ_END_KEY             = 86
    CHAFA_TERM_SEQ_END_CTRL_KEY        = 87
    CHAFA_TERM_SEQ_END_SHIFT_KEY       = 88
    CHAFA_TERM_SEQ_INSERT_KEY          = 89
    CHAFA_TERM_SEQ_INSERT_CTRL_KEY     = 90
    CHAFA_TERM_SEQ_INSERT_SHIFT_KEY    = 91
    CHAFA_TERM_SEQ_DELETE_KEY          = 92
    CHAFA_TERM_SEQ_DELETE_CTRL_KEY     = 93
    CHAFA_TERM_SEQ_DELETE_SHIFT_KEY    = 94

    CHAFA_TERM_SEQ_F1_KEY        = 95
    CHAFA_TERM_SEQ_F1_CTRL_KEY   = 96
    CHAFA_TERM_SEQ_F1_SHIFT_KEY  = 97
    CHAFA_TERM_SEQ_F2_KEY        = 98
    CHAFA_TERM_SEQ_F2_CTRL_KEY   = 99
    CHAFA_TERM_SEQ_F2_SHIFT_KEY  = 100
    CHAFA_TERM_SEQ_F3_KEY        = 101
    CHAFA_TERM_SEQ_F3_CTRL_KEY   = 102
    CHAFA_TERM_SEQ_F3_SHIFT_KEY  = 103
    CHAFA_TERM_SEQ_F4_KEY        = 104
    CHAFA_TERM_SEQ_F4_CTRL_KEY   = 105
    CHAFA_TERM_SEQ_F4_SHIFT_KEY  = 106
    CHAFA_TERM_SEQ_F5_KEY        = 107
    CHAFA_TERM_SEQ_F5_CTRL_KEY   = 108
    CHAFA_TERM_SEQ_F5_SHIFT_KEY  = 109
    CHAFA_TERM_SEQ_F6_KEY        = 110
    CHAFA_TERM_SEQ_F6_CTRL_KEY   = 111
    CHAFA_TERM_SEQ_F6_SHIFT_KEY  = 112
    CHAFA_TERM_SEQ_F7_KEY        = 113
    CHAFA_TERM_SEQ_F7_CTRL_KEY   = 114
    CHAFA_TERM_SEQ_F7_SHIFT_KEY  = 115
    CHAFA_TERM_SEQ_F8_KEY        = 116
    CHAFA_TERM_SEQ_F8_CTRL_KEY   = 117
    CHAFA_TERM_SEQ_F8_SHIFT_KEY  = 118
    CHAFA_TERM_SEQ_F9_KEY        = 119
    CHAFA_TERM_SEQ_F9_CTRL_KEY   = 120
    CHAFA_TERM_SEQ_F9_SHIFT_KEY  = 121
    CHAFA_TERM_SEQ_F10_KEY       = 122
    CHAFA_TERM_SEQ_F10_CTRL_KEY  = 123
    CHAFA_TERM_SEQ_F10_SHIFT_KEY = 124
    CHAFA_TERM_SEQ_F11_KEY       = 125
    CHAFA_TERM_SEQ_F11_CTRL_KEY  = 126
    CHAFA_TERM_SEQ_F11_SHIFT_KEY = 127
    CHAFA_TERM_SEQ_F12_KEY       = 128
    CHAFA_TERM_SEQ_F12_CTRL_KEY  = 129
    CHAFA_TERM_SEQ_F12_SHIFT_KEY = 130

    CHAFA_TERM_SEQ_RESET_COLOR_FG   = 131
    CHAFA_TERM_SEQ_RESET_COLOR_BG   = 132
    CHAFA_TERM_SEQ_RESET_COLOR_FGBG = 133

    CHAFA_TERM_SEQ_RESET_SCROLLING_ROWS = 134

    CHAFA_TERM_SEQ_SAVE_CURSOR_POS    = 135
    CHAFA_TERM_SEQ_RESTORE_CURSOR_POS = 136

    CHAFA_TERM_SEQ_SET_SIXEL_ADVANCE_DOWN  = 137
    CHAFA_TERM_SEQ_SET_SIXEL_ADVANCE_RIGHT = 138

    CHAFA_TERM_SEQ_ENABLE_ALT_SCREEN  = 139
    CHAFA_TERM_SEQ_DISABLE_ALT_SCREEN = 140

    CHAFA_TERM_SEQ_BEGIN_SCREEN_PASSTHROUGH = 141
    CHAFA_TERM_SEQ_END_SCREEN_PASSTHROUGH   = 142
    CHAFA_TERM_SEQ_BEGIN_TMUX_PASSTHROUGH   = 143
    CHAFA_TERM_SEQ_END_TMUX_PASSTHROUGH     = 144

    CHAFA_TERM_SEQ_BEGIN_KITTY_IMMEDIATE_VIRT_IMAGE_V1 = 145

    CHAFA_TERM_SEQ_QUERY_PRIMARY_DEVICE_ATTRIBUTES = 146
    CHAFA_TERM_SEQ_PRIMARY_DEVICE_ATTRIBUTES       = 147

    CHAFA_TERM_SEQ_QUERY_TEXT_AREA_SIZE_CELLS = 148
    CHAFA_TERM_SEQ_TEXT_AREA_SIZE_CELLS       = 149

    CHAFA_TERM_SEQ_QUERY_TEXT_AREA_SIZE_PX = 150
    CHAFA_TERM_SEQ_TEXT_AREA_SIZE_PX       = 151

    CHAFA_TERM_SEQ_QUERY_CELL_SIZE_PX = 152
    CHAFA_TERM_SEQ_CELL_SIZE_PX       = 153

    CHAFA_TERM_SEQ_MAX                                 = 154


#
# === Passthrough ===
#

class Passthrough(IntEnum):
    CHAFA_PASSTHROUGH_NONE    = 0
    CHAFA_PASSTHROUGH_SCREEN  = 1
    CHAFA_PASSTHROUGH_TMUX    = 2
    CHAFA_PASSTHROUGH_MAX     = 3


#
# === Tuck ===
#

class Tuck(IntEnum):
    CHAFA_TUCK_STRETCH        = 0
    CHAFA_TUCK_FIT            = 1
    CHAFA_TUCK_SHRINK_TO_FIT  = 2
    CHAFA_TUCK_MAX            = 3


#
# === Align ===
#
    
class Align(IntEnum):
    CHAFA_ALIGN_START   = 0
    CHAFA_ALIGN_END     = 1
    CHAFA_ALIGN_CENTER  = 2
    CHAFA_ALIGN_MAX     = 3


#
# === Quirks ===
#

class Quirks(IntEnum):
    CHAFA_TERM_QUIRK_SIXEL_OVERSHOOT = (1 << 0)