name: 📬 Deliver from Cirrus

on:
  check_suite:
    type: ['completed']

jobs:
  upload_all_cirrus:
    name: 📬 Deliver to PyPi
    if: > 
      github.event.check_suite.app.name   == 'Cirrus CI' &&
      github.event.check_suite.conclusion == 'success' &&

    runs-on: ubuntu-latest
    steps:
    - name: Downloading artifacts
      run: |
      wget https://api.cirrus-ci.com/v1/artifact/github/GuardKenzie/chafa.py/macos_arm_wheels/wheels.zip macos.zip
      wget https://api.cirrus-ci.com/v1/artifact/github/GuardKenzie/chafa.py/linux_arm_wheels/wheels.zip linux.zip
      unzip macos.zip
      unzip linux.zip
      mv wheelhouse dist
      


    - name: Uploading to PyPi
      uses: pypa/gh-action-pypi-publish@v1.8.5
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}